### ISSUE TITLE
Initiative tracker

### ISSUE THREAD

**Issue by andrasadam93** [vpeter1119/mcrpc-discord-bot#25]
### **Description**
A user can start an initiative tracker. Then any user can add any number of entries to that tracker. One entry should consist of: the submitter, the character name and the initiative number. Then, the user who started the tracker can launch the combat. With simple 'next' commands it should jump to the next people - by making a mention of the submitter of that entry so that they pay attention and prepare. 

### **Technical details**
**%init launch** --> this launches the tracker
- Make sure that only one can be launched at a time
- If nothing happens for a while then stop it automatically

**%init add** <CharName> <InitNumber>
- If no number is given then invalid entry
- If CharName already exists then invalid entry
- Init number to be between 0-50, whole number [MAX INIT VALUE](https://rpg.stackexchange.com/questions/136696/how-high-can-a-pcs-initiative-bonus-get)

**%init remove** <CharName>
- CharName must exist

**%init modify** <CharName> <NewInitNumber>
- CharName must exist
- Init number to be between 0-50, whole number

**%init fight**
--> this displays the order and calls upon the first two players by a mention

**%init next**
--> makes a jump on the initiative tracker.

So the whole list would be an array of objects, similar to this:
```
[
  {"user": "xy", "charNam": "Mr. Cool Guy", "init":20},
  {"user": "xy", "charNam": "Mr. Cool Guy's familiar", "init":17},
  {"user": "xyzh", "charNam": "Mrs. Cool Girl", "init":6}
]
```
And since actual initiative number is not quite necessary we can simply always just keep track of the largest number (in this case 20) and subtract that from each entry when "next" is pressed. So after one round it would look like:
```
[
  {"user": "xy", "charNam": "Mr. Cool Guy", "init":0},
  {"user": "xy", "charNam": "Mr. Cool Guy's familiar", "init":-3},
  {"user": "xyzh", "charNam": "Mrs. Cool Girl", "init":-14}
]
```
This still keeps the order (and between the two rounds all steps would make sure that whoever goes first then goes to the very last place).

Of course if for some reason we need to remember the original initiative we can introduce a new key-value to the entries (e.g. "displayInit": x which remains untouched)

### **Possible extra features**
- The user who started the tracker can also add further entries which are not visible for others
- Ready action to be incorporated somehow

**Comment by vpeter1119** [comment]
Looks cool, but very much like this:

https://avrae.io/commands#init

Do we need a separate unit tracker?

**Comment by andrasadam93** [comment]
I hate that Avrae thought of everything. Though I could have checked first :D
